### ISSUE TITLE
Uh, the vars/Debian and vars/Ubuntu files seem reversed?

### ISSUE THREAD

**Issue by rud** [Stouts/Stouts.mongodb#11]
Debian.yml sets:
```mongodb_repository: deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen```

Ubuntu.yml sets:
```mongodb_repository: deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen```

**Comment by fesor** [comment]
You may use my fork until #13 will be merged.

galaxy-roles.yml
```
---
 - src: https://github.com/fesor/Stouts.mongodb
   name: Stouts.mongodb
```
