### ISSUE TITLE
Run with security after creating user?

### ISSUE THREAD

**Issue by ShawnStrickland** [Stouts/Stouts.mongodb#8]
Is there a way I can restart services using the auth flag?  Right now I'm able to start and create a user in mongo, but then I'd like to restart using the --auth flag so I can limit interaction with the db.

 
    roles:
      - Stouts.mongodb
      - Stouts.nodejs

    vars:
      mongodb_conf_bind_ip: 127.0.0.1
      mongodb_conf_auth: no

    tasks:
      - name: Ensure Mongodb is started     
        service: name=mongod state=started

    post_tasks:
      - name: Generate MongoDB Super User
        mongodb_user: database=admin user=superuser password=daroots state=present

**Comment by ShawnStrickland** [comment]
I re-thought how to do it and got what I needed with something like this:


    vars:
      mongodb_conf_bind_ip: 0.0.0.0
      mongodb_conf_auth: yes

    post_tasks:
      - name: Generate MongoDB Test User
        mongodb_user: "database=test user=testuser password=roles='readWrite' state=present"

      - name: Generate MongoDB Super User
        mongodb_user: "database=admin user=superuser password=roles='readWriteAnyDatabase,dbAdminAnyDatabase,userAdminAnyDatabase' state=present"

Seems like assigning all users I needed, then follow with the super user will allow me to create users while also using `--auth` flag.

**Comment by pulse00** [comment]
@ShawnStrickland i'm trying the same thing, but your snippet above does not work, as from what i understand here's what happening:

1. The mongodb role installs mongodb and sets the `auth` flag to `yes` in `mongo.conf`
2. In the post task, you're creating the admin user

However, at that time, the mongodb server has already been restarted, which means you get `database error: not authorized for query on test.system.users` in the playbook.

@Stouts what's the proposed solution for adding administrative users with this role?
